### ISSUE TITLE
Deflect Seals don't work when enemy iniates attack

### ISSUE THREAD

**Issue by Amorsted** [Andu2/FEH-Mass-Simulator#112]
I was testing with Boey.

Deflect reduces the 2nd consecutive attack only when the challenger (Boey) is initiating. When the enemy initiates, the 2nd consecutive attack is not reduced by 80% damage.

**Comment by jyc8** [comment]
Deflect Missile seems to be working fine and Deflect Magic does not work against Staff and Dragonstones. Which seal were you testing?

**Comment by Amorsted** [comment]
I've attached the sample csv file.
Challenger: Boey
Enemy: Delthea
Seal: Deflect Magic
Initiator: Enemy

If I have Initiator as the Challenger, everything works correctly. The bug only seems to appear when the Enemy is the Initiator.

[feh_simulator_2018-3-13_Boey_Initiator.zip](https://github.com/Andu2/FEH-Mass-Simulator/files/1808307/feh_simulator_2018-3-13_Boey_Initiator.zip)

**Comment by Simmony** [comment]
Hi, I encountered the same issue:
Challenger: Robin (Fallen Heroes), no merges
Nature: -SPD + RES 
Skills: Fury in A slot
Seal: Deflect Melee
Setup: Enemy initiates attack only
Problem: The damage is only reduced when the enemy is using a Brave weapon, but only on the second hit. Examples: Ogma does  13/3/13/3 (gets killed) and Elincia does 23/5/23 (killing Robin) when Robin should win both fights. 

The other seals doesn't seem to be working as well, as previously mentioned. Examples: Jeorge and Fallen Takumi both do full damage twice when attacking him, and all Red Tome users too when using Deflect Magic.

**Comment by jyc8** [comment]
This is what happens when I tried Boey + Deflect Magic vs Delthea:

[Outcome](https://imgur.com/a/r87Ir)

I believe you are not counting the counterattack done by the challenger. For example, Delthea attacks Boey, Boey counters and breaks Delthea's consecutive attack, Delthea attacks again due to speed bonus.

Similarily, Ogma and Elincia both gets countered by Robin after the first double brave weapon attack, which breaks consecutive attack. Faye is working because she uses Firesweep bow and does not receive a counterattack in between her attacks.

Let me know if I am wrong about counterattacks breaking consecutive attack checks on deflect seals.

**Comment by Simmony** [comment]
I think I misread the text then, my bad. I thought it accounted for all attacks after the initial one... Should be no issue here, just confusing text!

**Comment by jyc8** [comment]
No worries, I never tested the Deflect seals in game, just Urvan when Ike came out and assumed they follow the same mechanics haha.

**Comment by Amorsted** [comment]
Well glad I am not the only one who misread the text then. I was thinking the same all consecutive attacks after the initial one. I double checked and tested it at Sluice Gate to make sure.

Sorry for wasting your time!

**Comment by jyc8** [comment]
No problem, stuff like this confirms the correctness of the sim's implementation!
