### ISSUE TITLE
Brave Ephraim's Garm doesn't when enemy initiates

### ISSUE THREAD

**Issue by PrinceGrimm** [Andu2/FEH-Mass-Simulator#170]
Ephraim doesn't get the guaranteed follow-up attack from Garm's effect when enemy initiates while he's buffed. It does work when he initiates though.

**Comment by ajz003** [comment]
The code for Garm is present at [line 8220](https://github.com/Andu2/FEH-Mass-Simulator/blob/6a19a5acb06bcdddd98b79d2343682b2074756ea/code.js#L8220-L8228) under the comment "// Check for auto follow-up skills" section:

`		if (this.hasExactly("Garm")){
			if (this.buffs.atk != 0 || this.buffs.spd != 0 || this.buffs.def != 0 || this.buffs.res != 0
				|| (this.hasExactly("Armored Boots") && this.combatStartHp/this.maxHp == 1)
				|| this.moveBuffed
				){
				thisAttackRank++;
				thisAttackRankChanged = true;
			}
		}`

However, it's not there in the  "// Check for auto follow-up counters" section [between lines 8231-8279](https://github.com/Andu2/FEH-Mass-Simulator/blob/6a19a5acb06bcdddd98b79d2343682b2074756ea/code.js#L8231-L8279)

I think this is the issue. This means that Garm doesn't work because it's not registered as an auto follow-up counter. I think this somewhere in the auto follow-up counters section will fix the issue:

`		if (enemy.hasExactly("Garm")){
			if (this.buffs.atk != 0 || this.buffs.spd != 0 || this.buffs.def != 0 || this.buffs.res != 0
				|| (this.hasExactly("Armored Boots") && this.combatStartHp/this.maxHp == 1)
				|| this.moveBuffed
				){
				thisAttackRank++;
				thisAttackRankChanged = true;
				console.log("YOOOOOOOOOOOOOOOOOOOO " +this);
			}
		}`


Let me know if this works! (If it doesn't, then this is embarrassing...) I'm just starting to learn JavaScript and I want to see if I can contribute a bit.

**Comment by jyc8** [comment]
Thanks! I forgot that counters like Quick Riposte are follow-up attacks too.
